services:
  db_pos:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass_pos
      - POSTGRES_USER=user_pos
      - POSTGRES_DB=db_pos
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
    depends_on:
        - db_pos
  backend:
      container_name: backend-nodejs-pos
      build: './backend'
      volumes:
        - './backend:/app'
        - '/app/node_modules'
        - '/app/.next'
      tty: true
      ports:
        - '8080:8080'
      environment:
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true
        - TZ=Asia/Bangkok
      depends_on:
        - db_pos
  frontend:
    container_name: frontend-nextjs-pos
    build: './frontend'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
      - '/app/.next'
    tty: true
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - TZ=Asia/Bangkok
    depends_on:
      - db_pos
      - backend
    #stdin_open: true
    # depends_on:
    #   - db
    #   - backend
