services:
  frontend:
    container_name: frontend-nextjs-pos
    build: './frontend'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
      - '/app/.next'
    tty: true
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Bangkok
    #stdin_open: true
    # depends_on:
    #   - db
    #   - backend